"""initial alembic

Revision ID: 20e908f3c2d7
Revises: 
Create Date: 2026-05-29 07:51:56.873751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e908f3c2d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('department_name', sa.String(), nullable=False),
    sa.Column('head_of_department', sa.String(), nullable=True),
    sa.Column('activity', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('department_name'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=25), nullable=True),
    sa.Column('report', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_table('department')
    # ### end Alembic commands ###
