"""alembic test alembic

Revision ID: fad032c8bf70
Revises: 20e908f3c2d7
Create Date: 2026-05-29 23:27:20.324703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad032c8bf70'
down_revision: Union[str, Sequence[str], None] = '20e908f3c2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_table('department')
    op.create_table('Department',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('head_of_department', sa.String(), nullable=True),
    sa.Column('activity', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('pasword', sa.String(length=25), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pasword'),
    sa.UniqueConstraint('role'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=25), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_name'], ['Department.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Attendance',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('Employee_name', sa.String(length=80), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Employee_name'], ['Employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Employee_name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Employee_name'], ['Employees.id'], ),
    sa.ForeignKeyConstraint(['position'], ['Employees.position'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('Attendance')
    op.drop_table('Employees')
    op.drop_table('users')
    op.drop_table('Department')
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('department', sa.VARCHAR(length=25), nullable=True),
    sa.Column('report', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('department',
    sa.Column('department_name', sa.VARCHAR(), nullable=False),
    sa.Column('head_of_department', sa.VARCHAR(), nullable=True),
    sa.Column('activity', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('department_name'),
    sa.UniqueConstraint('department_name')
    )
    # ### end Alembic commands ###
